# Generated by Django 4.2 on 2025-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_created_at_alter_concert_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='available_tickets',
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
