# Generated by Django 4.2 on 2025-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='available_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
